
spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tech?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  application:
    name: backend
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY:}
      chat:
        model: qwen-turbo
      embedding:
        model: text-embedding-v2
    vectorstore:
      redis:
        uri: redis://localhost:6379
        initialize-schema: true
        index-name: teaching-resources
        prefix: "vector:"
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# 阿里云OSS配置
aliyun:
  oss:
    access-key-id: ${ALIYUN_OSS_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_OSS_ACCESS_KEY_SECRET}
    bucket-name: ${ALIYUN_OSS_BUCKET_NAME:tech-czq}
    endpoint: ${ALIYUN_OSS_ENDPOINT:oss-cn-beijing.aliyuncs.com}
    custom-domain: ${ALIYUN_OSS_CUSTOM_DOMAIN:}

logging:
  level:
    org.springframework.ai: debug
    com.alibaba.dashscope.api: debug
    com.alibaba.cloud.ai.dashscope.chat: debug
    com.mtm.backend: debug
server:
  port: 8082

jwt:
    secret: 1234567890qwertyuiopasdfghjklzxcvbnm
    expiration: 8640000 # 24 hours in seconds
