
spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tech?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ${DATABASE_PASSWORD:123456}
  application:
    name: backend
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY:sk-test-placeholder-key}
      chat:
        model: qwen-turbo
      embedding:
        model: text-embedding-v2
    vectorstore:
      redis:
        uri: redis://localhost:6379
        initialize-schema: true
        index-name: teaching-resources
        prefix: "vector:"
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


# 本地文件存储配置
local:
  file:
    storage:
      base-path: ${LOCAL_FILE_STORAGE_PATH:./uploads}
      base-url: ${LOCAL_FILE_STORAGE_URL:http://localhost:8082/files}
      max-file-size:
        document: 50
        audio: 100
      allowed-types:
        document: ["pdf", "doc", "docx", "ppt", "pptx", "txt", "md"]
        audio: ["mp3", "wav", "m4a", "flac"]

logging:
  level:
    org.springframework.ai: debug
    com.alibaba.dashscope.api: debug
    com.alibaba.cloud.ai.dashscope.chat: debug
    com.mtm.backend: debug
server:
  port: 8082

jwt:
    secret: ${JWT_SECRET:1234567890qwertyuiopasdfghjklzxcvbnm}
    expiration: ${JWT_EXPIRATION:86400} # 24 hours in seconds
