
spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 2000ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tech?useUnicode=true&characterEncoding=UTF-8&connectTimeout=30000&socketTimeout=60000
    username: root
    password: ${DATABASE_PASSWORD:123456}
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 20
  application:
    name: backend
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY:sk-test-placeholder-key}
      chat:
        model: qwen-turbo
        options:
          timeout: 60s
      embedding:
        model: text-embedding-v2
        options:
          timeout: 120s
          max-retries: 3
          retry-delay: 1s
    vectorstore:
      redis:
        uri: redis://localhost:6379
        initialize-schema: true
        index-name: teaching-resources
        prefix: "vector:"
        connection-timeout: 10s
        read-timeout: 30s
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


# 本地文件存储配置
local:
  file:
    storage:
      base-path: ${LOCAL_FILE_STORAGE_PATH:./uploads}
      base-url: ${LOCAL_FILE_STORAGE_URL:http://localhost:8082/files}
      max-file-size:
        document: 50
        audio: 100
      allowed-types:
        document: ["pdf", "doc", "docx", "ppt", "pptx", "txt", "md"]
        audio: ["mp3", "wav", "m4a", "flac"]

logging:
  level:
    org.springframework.ai: debug
    com.alibaba.dashscope.api: debug
    com.alibaba.cloud.ai.dashscope.chat: debug
    com.alibaba.cloud.ai.dashscope.embedding: debug
    com.mtm.backend: debug
    reactor.netty: debug
    org.springframework.web.reactive.function.client: debug

# 监控和健康检查配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,dashscope
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    dashscope:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
server:
  port: 8082

jwt:
    secret: ${JWT_SECRET:1234567890qwertyuiopasdfghjklzxcvbnm}
    expiration: ${JWT_EXPIRATION:604800} # 7 days in seconds (7*24*60*60)
